# Optimized workflow for building and deploying a Hugo site to GitHub Pages
name: Ian Loam

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.149.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Cache Hugo
        uses: actions/cache@v4
        with:
          path: ~/hugo
          key: hugo-${{ env.HUGO_VERSION }}
          restore-keys: |
            hugo-

      - name: Install Hugo CLI
        run: |
          if [ ! -f ~/hugo/hugo ]; then
            wget -O ${{ runner.temp }}/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz \
            && tar -xzf ${{ runner.temp }}/hugo.tar.gz -C ${{ runner.temp }} \
            && mkdir -p ~/hugo \
            && mv ${{ runner.temp }}/hugo ~/hugo/hugo
          fi
          chmod +x ~/hugo/hugo
          echo ~/hugo >> $GITHUB_PATH

      - name: Cache npm dependencies
        uses: actions/cache@v4
        if: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]]"
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json') }}
          restore-keys: |
            npm-

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache
          key: hugo-modules-${{ hashFiles('go.sum', 'hugo.toml') }}
          restore-keys: |
            hugo-modules-

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          HUGO_CACHEDIR: /tmp/hugo_cache
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --gc \
            --cleanDestinationDir

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
